# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platform"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1095, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 40, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 100, 81, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 220, 71, 31))
        self.label_5.setObjectName("label_5")
        self.btn_newKey = QtWidgets.QToolButton(self.centralwidget)
        self.btn_newKey.setGeometry(QtCore.QRect(590, 50, 111, 21))
        self.btn_newKey.setObjectName("btn_newKey")
        self.btn_en = QtWidgets.QToolButton(self.centralwidget)
        self.btn_en.setGeometry(QtCore.QRect(40, 400, 81, 41))
        self.btn_en.setObjectName("btn_en")
        self.btn_de = QtWidgets.QToolButton(self.centralwidget)
        self.btn_de.setGeometry(QtCore.QRect(240, 400, 81, 41))
        self.btn_de.setObjectName("btn_de")
        self.btn_sign = QtWidgets.QToolButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(600, 400, 81, 41))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verifi = QtWidgets.QToolButton(self.centralwidget)
        self.btn_verifi.setGeometry(QtCore.QRect(890, 400, 81, 41))
        self.btn_verifi.setObjectName("btn_verifi")
        self.txt_plain = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain.setGeometry(QtCore.QRect(120, 110, 311, 91))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_cipher = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipher.setGeometry(QtCore.QRect(120, 230, 311, 91))
        self.txt_cipher.setObjectName("txt_cipher")
        self.txt_infor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_infor.setGeometry(QtCore.QRect(580, 110, 311, 91))
        self.txt_infor.setObjectName("txt_infor")
        self.txt_sign = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(580, 230, 311, 91))
        self.txt_sign.setObjectName("txt_sign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "PLAIN TEXT"))
        self.label_3.setText(_translate("MainWindow", "CIPHER TEXT"))
        self.label_4.setText(_translate("MainWindow", "INFORMATION"))
        self.label_5.setText(_translate("MainWindow", "SIGNATURE"))
        self.btn_newKey.setText(_translate("MainWindow", "GENERATE KEY"))
        self.btn_en.setText(_translate("MainWindow", "ENCRYPT"))
        self.btn_de.setText(_translate("MainWindow", "DECRYPT"))
        self.btn_sign.setText(_translate("MainWindow", "SIGN"))
        self.btn_verifi.setText(_translate("MainWindow", "VERIFI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
